import { mkdirSync, copyFileSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "../assets/ghostty");
const T3CODE = process.env.T3CODE_DIR || join(process.env.HOME, "Projects/Repos/t3code");
const GHOSTTY_SRC = join(T3CODE, "apps/web/src/terminal/ghostty");

if (typeof Bun === "undefined") {
  console.error("run me with bun: bun app/scripts/rebuild-ghostty.mjs");
  process.exit(1);
}
if (!existsSync(join(GHOSTTY_SRC, "surface.ts"))) {
  console.error(`t3code checkout not found at ${T3CODE} — set T3CODE_DIR`);
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });

const ASSETS = [
  ["vendor/ghostty-vt.wasm", "ghostty-vt.wasm"],
  ["vendor/ghostty-write-pty.wasm", "ghostty-write-pty.wasm"],
  ["fonts/SymbolsNerdFontMono-Regular.woff2", "SymbolsNerdFontMono-Regular.woff2"]
];
for (const [from, to] of ASSETS) copyFileSync(join(GHOSTTY_SRC, from), join(OUT, to));

const entry = join(OUT, ".entry.ts");
writeFileSync(entry, [
  `export { GhosttyTerminalSurface } from ${JSON.stringify(join(GHOSTTY_SRC, "surface.ts"))};`,
  `export { GhosttyTerminalCore } from ${JSON.stringify(join(GHOSTTY_SRC, "core.ts"))};`
].join("\n"));

const UTILS_SHIM = `
export function isMacPlatform(platform) { return /mac|iphone|ipad|ipod/i.test(platform); }
`;

const FONTS_SHIM = `
function cssFontFamilies(input) {
  const families = input.split(",").map((name) => {
    const bare = name.trim().replace(/^["']|["']$/g, "").trim();
    if (!bare) return "";
    return /^[a-zA-Z][a-zA-Z0-9 _-]*$/.test(bare) ? bare : JSON.stringify(bare);
  }).filter((name) => name.length > 0);
  return families.length > 0 ? families.join(", ") : null;
}
const VARIANTS = ["normal 400", "normal 700", "italic 400", "italic 700"];
const GLYPHS = ["i", "M", "W", "0", "@", "#", ".", " "];
let probe;
export function isMonospaceFamily(family) {
  const families = cssFontFamilies(family);
  if (families === null) return true;
  try {
    if (probe === undefined) probe = document.createElement("canvas").getContext("2d");
    if (probe === null) return true;
    for (const variant of VARIANTS) {
      probe.font = variant + " 32px " + families + ", monospace";
      const widths = GLYPHS.map((glyph) => probe.measureText(glyph).width);
      const first = widths[0];
      if (first > 0 && widths.every((w) => Number.isFinite(w) && w > 0)
        && !widths.every((w) => Math.abs(w - first) < 0.01)) return false;
    }
    return true;
  } catch { return true; }
}
`;

const urlAssets = {
  name: "served-url",
  setup(build) {
    build.onResolve({ filter: /\?url(&no-inline)?$/ }, (args) => ({
      path: `/assets/ghostty/${basename(args.path.split("?")[0])}`,
      namespace: "served-url"
    }));
    build.onLoad({ filter: /.*/, namespace: "served-url" }, (args) => ({
      contents: `export default ${JSON.stringify(args.path)};`,
      loader: "js"
    }));
    build.onResolve({ filter: /(^|\/)lib\/utils$/ }, () => ({ path: "utils", namespace: "shim" }));
    build.onResolve({ filter: /(^|\/)appearanceFonts$/ }, () => ({ path: "fonts", namespace: "shim" }));
    build.onLoad({ filter: /.*/, namespace: "shim" }, (args) => ({
      contents: args.path === "utils" ? UTILS_SHIM : FONTS_SHIM,
      loader: "js"
    }));
  }
};

const result = await Bun.build({
  entrypoints: [entry],
  target: "browser",
  format: "esm",
  minify: false,
  plugins: [urlAssets]
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
const bundled = await result.outputs[0].text();
const revision = existsSync(join(T3CODE, "native/libghostty-vt/VERSION"))
  ? readFileSync(join(T3CODE, "native/libghostty-vt/VERSION"), "utf8").trim()
  : "unknown";
const banner = `/* generated by app/scripts/rebuild-ghostty.mjs — do not edit by hand.
   source: t3code apps/web/src/terminal/ghostty (MIT, T3 Tools Inc)
   libghostty-vt revision: ${revision} — see assets/ghostty/NOTICE.md */\n`;
writeFileSync(join(OUT, "ghostty.mjs"), banner + bundled);
await Bun.$`rm ${entry}`;

writeFileSync(join(OUT, "NOTICE.md"), `# Third-party notices — assets/ghostty

## t3code ghostty web adapter

\`ghostty.mjs\` is bundled from the browser adapter at
\`apps/web/src/terminal/ghostty\` in [t3code](https://github.com/t3dotgg/t3code)
(MIT, T3 Tools Inc). Regenerate with \`bun app/scripts/rebuild-ghostty.mjs\`
against a t3code checkout (\`T3CODE_DIR\` overrides the default path).

## Ghostty / libghostty-vt

\`ghostty-vt.wasm\` and \`ghostty-write-pty.wasm\` are reproducible builds of
[libghostty-vt](https://github.com/ghostty-org/ghostty) (MIT) produced by
t3code's \`apps/web/scripts/build-libghostty-wasm.sh\`.

- Vendored revision: \`${revision}\`

## Symbols Nerd Font Mono

\`SymbolsNerdFontMono-Regular.woff2\` is the symbols-only Nerd Font (MIT),
vendored so prompt glyphs render without a locally installed Nerd Font.
`);

console.log(`ghostty.mjs ${(bundled.length / 1024).toFixed(0)}kB + wasm + font → ${OUT}`);
